### PR TITLE
Fix typo in google_monitoring_uptime_check_config

### PR DESCRIPTION
**Pull request by rwblokzijl**
Resolves https://github.com/hashicorp/terraform-provider-google/issues/10106

### CODE REVIEW

**Comment by megan07** [comment]
Hi @rwblokzijl ! Thanks for this PR! This code is actually generated, so if you'd like to change it upstream, you can fix it here: https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/products/monitoring/api.yaml#L1719 (it will fix both the validation and the documentation). Let me know if you don't have time for this fix, and I can make it as well. Thanks!

**Comment by rwblokzijl** [comment]
Hi, thanks for the response. I will make the PR :)

**Comment by rwblokzijl** [comment]
PR here: https://github.com/GoogleCloudPlatform/magic-modules/pull/5276

**Comment by megan07** [comment]
Thank you!

**Pull request closed without merging**
