### PR TITLE
3.54.0 - release notes and cherry pick

### PR DESCRIPTION
**Pull request by ScottSuarez**
contains the release notes and cherry-pick of [c216b91568068600a59b99c375d42f9400d2e943](https://github.com/hashicorp/terraform-provider-google/commit/c216b91568068600a59b99c375d42f9400d2e943)

### CODE REVIEW

**Comment by ScottSuarez** [comment]
hi @rileykarson, I'm going to be out of town for the remainder of the week but just wanted to make sure I got this out there. Could you shepherd this cherrypick and audit these notes before the release Monday?

There was a failing test on a newly added resource [TestAccPrivatecaCertificateAuthority_privatecaCertificateAuthorityCmekExample](https://ci-oss.hashicorp.engineering/project.html?tab=testDetails&testNameId=7482435357168603072&projectId=GoogleCloudBeta&buildTypeId=GoogleCloudBeta_ProviderGoogleCloudBetaGoogleProject) in tpgb. Could you take a look at it? I think we should be good to go. Since it's a new resource any flaws won't break existing users.

**Review by c2thorn — APPROVED** [review]

**Review by rileykarson — APPROVED** [review]

**Comment by m1n0** [comment]
hi, ```bigquery: made incompatible changes to the `google_bigquery_table.schema` field to cause the resource to be recreated ``` seems like a quite disruptive change for a small version bump. I see that 54 was unreleased but I could not find any info on that, what happened here please?

**Comment by rileykarson** [comment]
We treated this as a compatible change, eg one that we can release in a minor release. The change should cause Terraform to attempt to recreate the resource in cases where the API would have returned an error indicating that changing from one schema to another was impossible. However the interaction with some other behaviour(s) on the field caused a larger impact than expected, and we'll revert for the next release. See https://github.com/hashicorp/terraform-provider-google/issues/8282

We plan to reintroduce the change during the `3.X` release series at this time, although feedback is appreciated. https://github.com/hashicorp/terraform-provider-google/issues/1144 is a good place for it, I think.

**Comment by maroshmka** [comment]
hello @rileykarson, I've wrote feedback in https://github.com/hashicorp/terraform-provider-google/issues/1144#issuecomment-768930080, but I see issue is closed, so pinging here :) thanks!

**Pull request merged**
