### PR TITLE
fix linter in tpg

### PR DESCRIPTION
**Pull request by ScottSuarez**
Helps with https://github.com/hashicorp/terraform-provider-google/issues/9145

ref:
https://github.com/golangci/golangci-lint/pull/2017

### CODE REVIEW

**Review by melinath — CHANGES_REQUESTED** [review]
I still get the following errors locally: 

```
google/resource_container_cluster_test.go:2366:6: func `testAccContainerCluster_updateVersion` is unused (unused)
google/resource_container_node_pool_test.go:1284:6: func `testAccContainerNodePool_version` is unused (unused)
google/resource_container_node_pool_test.go:1308:6: func `testAccContainerNodePool_updateVersion` is unused (unused)
google/resource_container_cluster_test.go:2644:6: func `testAccContainerCluster_withNodePoolLowerVersion` is unused (unused)
google/resource_container_cluster_test.go:2351:6: func `testAccContainerCluster_withLowerVersion` is unused (unused)
google/resource_container_cluster_test.go:2665:6: func `testAccContainerCluster_withNodePoolUpdateVersion` is unused (unused)
```

**Comment by ScottSuarez** [comment]
> I still get the following errors locally that aren't in CI: 
> 
> 
> 
> ```
> 
> google/resource_container_cluster_test.go:2366:6: func `testAccContainerCluster_updateVersion` is unused (unused)
> 
> google/resource_container_node_pool_test.go:1284:6: func `testAccContainerNodePool_version` is unused (unused)
> 
> google/resource_container_node_pool_test.go:1308:6: func `testAccContainerNodePool_updateVersion` is unused (unused)
> 
> google/resource_container_cluster_test.go:2644:6: func `testAccContainerCluster_withNodePoolLowerVersion` is unused (unused)
> 
> google/resource_container_cluster_test.go:2351:6: func `testAccContainerCluster_withLowerVersion` is unused (unused)
> 
> google/resource_container_cluster_test.go:2665:6: func `testAccContainerCluster_withNodePoolUpdateVersion` is unused (unused)
> 
> ```

Yeah this is due to a newer version of the linter. This error is legitimate. The tests that use these functions early use a t.skip which is considered an early return. We will need to fix those tests to be conditional skips

**Comment by melinath** [comment]
@ScottSuarez why do those errors not show up in CI? Is it on an old version of the linter?

**Review by melinath — APPROVED** [review]
LGTM - definitely an improvement over the current state. I think it doesn't quite close the ticket as-is, though, since there are still errors that are showing up locally but not in CI.

**Review by melinath — APPROVED** [review]
LGTM - definitely an improvement over the current state. I think it doesn't quite close the ticket as-is, though, since there are still errors that are showing up locally but not in CI.

**Pull request merged**
