### PR TITLE
Add the ability to create a big query view with schema

### PR DESCRIPTION
**Pull request by avercoutere**
Make a 2 steps creation/update when the table is a view and it contains a schema. Google API doesn't support creating/modifying a view query with setting a schema at the same time.

### CODE REVIEW

**Comment by avercoutere** [comment]
Fix #9096

**Comment by rileykarson** [comment]
Note: we likely want to wait on a resolution for issuetracker.google.com/171967405 before moving forward with this change

**Comment by tchiotludo** [comment]
@rileykarson : The google ticket 171967405 is not the same goal than this PR.

Google ticket 171967405 want to copy description from based tabled to the view. 
This PR only want to allow terraform to add description on the view (that can be a custom one and different from based table). 
The scope is larger with this PR since we can provide a description for any columns, example : I have an aggregation from many columns, the google ticket will not help in this case since no description will be forwarded on this standard case. 

This PR will allow to have the same behaviour and usage than the gcp console here : 
image
a simple manual description on columns of the view. 

Can this PR can be reconsidered please ? We have a lot of usage here that is completely blocked and this PR do exactly what we need. 

Thanks

**Comment by rileykarson** [comment]
@ScottSuarez: Is this a reasonable change to make w/o the issuetracker issue linked above? Not sure I understand the product well enough to make a call.

**Comment by ScottSuarez** [comment]
I think this is reasonable.

originally I tracked this ask to the api team and they refused this altercation on their side. I think this would be good QoL change

**Comment by ScottSuarez** [comment]
@rileykarson are we to consider allowing this then?

@c2thorn shall you assist in following this through or I?

**Comment by rileykarson** [comment]
Seems fine to me- y'all can choose between yourselves.

**Comment by tchiotludo** [comment]
@ScottSuarez @rileykarson @c2thorn any progress please ? seems the just need a reviewer here ?

**Comment by ScottSuarez** [comment]
I'll take over and review this change. I'll try to get to it this week.
Releases are paused for now for the holidays but we should have it in the release we do the second week of January.

Thank you for your patience.

**Comment by c2thorn** [comment]
Hey folks, I had already started work on this before @ScottSuarez realized.

> any progress please ? seems the just need a reviewer here ?

It is not as simple as just a review. The code change needed to be upstreamed to Magic Modules and also a test added to show the feature working correctly. I've made the upstream PR here: https://github.com/GoogleCloudPlatform/magic-modules/pull/5583

I'm having trouble getting a proper test going, but once that is complete we should be good to go.

**Comment by c2thorn** [comment]
upstream PR is merged, I will close this one.

**Pull request closed without merging**
