### PR TITLE
docs: Additional examples of import with condition for IAM binding resources

### PR DESCRIPTION
**Pull request by oleksiypavlenko**
Fixed the issue https://github.com/hashicorp/terraform-provider-google/issues/11338 by providing examples for importing:

- google_organization_iam_binding
- google_folder_iam_binding
- google_project_iam_binding

with condition block

### CODE REVIEW

**Comment by rileykarson** [comment]
FYI @megan07: Reviewer lottery didn't seem to work here (possibly due to the branch change?)

**Comment by megan07** [comment]
@rileykarson seems to have been a one-off thing, I can't find any reason why this particular PR wouldn't have triggered it but all others since have.

**Comment by rileykarson** [comment]
Got it!

Hey @oleksiypavlenko: do you mind making the change to the corresponding files under https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/website, which will update the `google-beta` provider as well? Thanks!

**Comment by oleksiypavlenko** [comment]
@rileykarson PR open with same changes to google-beta docs => https://github.com/GoogleCloudPlatform/magic-modules/pull/6002

**Comment by rileykarson** [comment]
superseded w/ https://github.com/hashicorp/terraform-provider-google/pull/11632

**Pull request closed without merging**
