### PR TITLE
Add support for configuring disk resource policies for google_compute_instance_template.

### LINKED ISSUE #6719: Add support for configuring disk resource policies for google_compute_instance_template
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment. If the issue is assigned to the "modular-magician" user, it is either in the process of being autogenerated, or is planned to be autogenerated soon. If the issue is assigned to a user, that user is claiming responsibility for the issue. If the issue is assigned to "hashibot", a community member has claimed the issue already.

### Description

Today, if managing disks with the `google_compute_disk` resource, you're able to set and manage resource policies (for things like scheduled snapshots, etc) on disks. When using instance templates (`google_compute_instance_template`) for example with a MIG, there is no ability to set the resource policies that should be attached to a disk when creating the template (consider stateful MIGs, where this would be incredibly helpful)

In the same way that you can attach resource policies to the disk resource, it would be great to be able to do the same with instance templates.

[instanceTemplates.insert](https://cloud.google.com/compute/docs/reference/rest/v1/instanceTemplates/insert) does seem to have support for this (`properties.disks[].initializeParams.resourcePolicies[]`), so it "should" just be a matter of surfacing the functionality in Terraform.

### New or Affected Resource(s)

* google_compute_instance_template

### Potential Terraform Configuration

```tf
resource "google_compute_instance_template" "template" {
  ..
  disk {
    source_image = ..
    resource_policies = [
      # similar to google_compute_disk, resource policy uris
    ]
  }
}
```

### References

* #5863 - discusses adding support for instance level resource policies (such as a placement policy) to the instance template, but does not specifically raise support for them on disks.

### PR DESCRIPTION
**Pull request by rayward**
Fixes #6719

Per documentation (and checked), https://pkg.go.dev/google.golang.org/api/compute/v0.beta#AttachedDiskInitializeParams only the resource policy _name_ is supported for instance templates, a uri can't be used. A link can be used in user code, but it will be converted to the resource name.

### CODE REVIEW

**Comment by ScottSuarez** [comment]
can you add this field to the documentation? Possibly an example there-in too?

**Comment by rayward** [comment]
@ScottSuarez I'm second guessing the decision to support self links on this field when the underlying API doesn't. Do you think I should keep this behaviour (of converting a link) or make it short names only, it's easy enough for a user to reference the name:

`resource_policies = [google_compute_resource_policy.my_snapshot_schedule.name]`

The `source` field for disks also doesn't support self-links for example - https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template#source

**Comment by rayward** [comment]
I've (tentatively) documented the field, but will adjust it pending the above question.

**Comment by ScottSuarez** [comment]
Hi, sorry for the delay on this. I was out of town. I spoke with my team on this and we prefer resources to reference each other by the `.id` property if possible. Its something we've consistently maintained within the provider.

**Comment by rayward** [comment]
> I spoke with my team on this and we prefer resources to reference each other by the `.id` property if possible.

I think `.id` is effectively interchangeable for `.self_link` from what I can see. In any case the resource itself only supports the short name so I can keep the conversion code in and update the documentation and example to use `.id`.

**Comment by ScottSuarez** [comment]
I'll focus on trying to merge this for you today! Sorry for the delay my friend :>

**Pull request merged**
