### PR TITLE
resourcemanager: adding "google_folders" data source

### PR DESCRIPTION
**Pull request by mikelaramie**
The goal of this PR is to add a new data source to the provider, `google_folders`, to allow terraform code to enumerate a list of folders within a parent object (org or folder).  

The code was modified from the existing `google_projects` data source to fit the needs of querying folders from the resourcemanager api v3.

### CODE REVIEW

**Review by slevenick — CHANGES_REQUESTED** [review]
Looks like the test fails with:
```
provider_test.go:278: Step 1/1 error: Check failed: Check 1/8 error: Not found: data.google_folders.my-folder in [root]
```

Are you able to run this test locally?

**Comment by mikelaramie** [comment]
It should pass now; I was running the wrong test locally, and got the failure you saw when I ran the right test.  Sorry about that!

```
❯ make testacc TEST=./google TESTARGS='-run=TestAccDataSourceGoogleFolders_basic'
==> Checking source code against gofmt...
==> Checking that code complies with gofmt requirements...
go generate  ./...
TF_ACC=1 TF_SCHEMA_PANIC_ON_ERROR=1 go test ./google -v -run=TestAccDataSourceGoogleFolders_basic -timeout 240m -ldflags="-X=github.com/hashicorp/terraform-provider-google/version.ProviderVersion=acc"
=== RUN   TestAccDataSourceGoogleFolders_basic
=== PAUSE TestAccDataSourceGoogleFolders_basic
=== CONT  TestAccDataSourceGoogleFolders_basic
--- PASS: TestAccDataSourceGoogleFolders_basic (17.50s)
PASS
ok  	github.com/hashicorp/terraform-provider-google/google	18.199s
```

**Comment by mikelaramie** [comment]
I also signed the CLA, so hopefully that check will pass now in MM

**Review by slevenick — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
