### PR TITLE
Add v3.47.0 changelog

### PR DESCRIPTION
**Pull request by c2thorn**

### CODE REVIEW

**Review by rileykarson — APPROVED** [review]

**Comment by thiagonache** [comment]
Hi folks,

Just a friendly question. How long are we expecting to release this version?

**Comment by c2thorn** [comment]
@thiagonache I can't say for sure, but usually before noon Pacific Time today.

**Comment by c2thorn** [comment]
@thiagonache google provider v3.47.0 now appears in https://releases.hashicorp.com/terraform-provider-google/

**Comment by thiagonache** [comment]
> @thiagonache google provider v3.47.0 now appears in https://releases.hashicorp.com/terraform-provider-google/

@c2thorn thanks a lot!!!!

**Pull request merged**
